//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskComments = new HashSet<TaskComment>();
            this.TimeLogs = new HashSet<TimeLog>();
        }
    
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Status { get; set; }
        public int AsigneeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Logged { get; set; }
        public Nullable<int> Estimated { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Project Project { get; set; }
        public virtual Project Project1 { get; set; }
        public virtual TaskPriority TaskPriority { get; set; }
        public virtual TaskPriority TaskPriority1 { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual TaskStatu TaskStatu1 { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual TaskType TaskType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeLog> TimeLogs { get; set; }
    }
}
